name: Create new Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'composer.json'
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
      -
        name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          CNAME: bits.labor.tools
          ACCESS_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: cd docs && npm i && npm run build
          BUILD_DIR: .vuepress/dist/